{
  pkgs,
  modulesPath,
  tools,
  ...
}:
{
  imports = [
    (modulesPath + "/installer/cd-dvd/installation-cd-minimal.nix")
    ../../systemModules/ssh.nix

  ];

  environment.systemPackages = [
    pkgs.kakoune
    pkgs.git

    (tools.make_commands_script {
      inherit pkgs;
      options = {
        forward_ssh = ''
          bore local 22 --to bore.pub
        '';

        local_install = ''
          git clone https://github.com/astaugaard/dotfiles.git
          cd dotfiles
          sudo ${pkgs.disko}/bin/disko --mode disko --flake .#$1

          sudo ${pkgs.nixos-install}/bin/nixos-install --no-channel-copy --no-root-password --flake .#$1
        '';
      };
    })
  ];

  services.openssh.enable = true;
  services.openssh.settings.PermitRootLogin = "no";
  services.openssh.settings.PasswordAuthentication = false;

  users.users.nixos.openssh.authorizedKeys.keys = [
    # allow access from phone
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKaAzkcBKKDe6jf2gmisI+uiizYPBq34k7S45ErozIsp Generated By Termius"
    # allow access from desktop (kindof redundent when running on desktop lol)
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIL2iCpKEzSNqZAr9+krmBI8k1eWJggH6nM1njUjLTv8z a@nixos"
  ];

}
