repositories:
  - name: longhorn
    url: https://charts.longhorn.io

releases:
  # Distributed storage
  - name: longhorn
    namespace: longhorn-system
    chart: longhorn/longhorn
    version: 1.6.2
    installed: false
