{
  pkgs,
  config,
  lib,
  pkgs-unstable,
  ...
}:
with builtins;
with lib;
{
  options.mysystem.ssh = {
    enable = mkOption {
      description = "enable system ssh";
      type = lib.types.bool;
      default = false;
    };
  };

  config = mkIf config.mysystem.tailscale.enable {
    services.openssh.enable = true;
    services.openssh.settings.PermitRootLogin = "no";
    users.users.a.openssh.authorizedKeys.keys = [
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKaAzkcBKKDe6jf2gmisI+uiizYPBq34k7S45ErozIsp Generated By Termius"
    ];
  };
}
