{
  pkgs,
  config,
  lib,
  pkgs-unstable,
  ...
}:
with builtins;
with lib;
{
  options.mysystem.ssh = {
    enable = mkOption {
      description = "enable system ssh";
      type = lib.types.bool;
      default = false;
    };

    root-login = mkOption {
      description = "allow root login with ssh";
      type = lib.types.bool;
      default = false;
    };
  };

  config = mkIf config.mysystem.ssh.enable {
    services.openssh.enable = true;
    services.openssh.settings.PermitRootLogin = if config.mysystem.ssh.root-login then "yes" else "no";
    users.users."${config.mysystem.user}".openssh.authorizedKeys.keys = [
      # allow access from phone
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKaAzkcBKKDe6jf2gmisI+uiizYPBq34k7S45ErozIsp Generated By Termius"
      # allow access from desktop (kindof redundent when running on desktop lol)
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBpkbotDwBlaulIHYkEFx3FkaNZKgnmlK7BMYfGpyieH a@nixos"
    ];
  };
}
