# based on: https://github.com/gvolpe/nix-config/blob/master/.github/workflows/home.yml
name: Home

on:
  pull_request:
  push:
    branches:
      - main
    paths-ignore:
      - 'configuration.nix'
      - '.gitignore'
      - 'systemModules/**'
      - 'secrets'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        config_name:
            - a

    steps:
      - uses: actions/checkout@v2.3.2
        with:
            submodules: 'true'

      - name: "Install Nix ❄️"
        uses: cachix/install-nix-action@v30

      - name: "Install Cachix ❄️"
        uses: cachix/cachix-action@v15
        with:
          name: estaugaard
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      # Needed because cachix is also installed by Home Manager
      - name: "Set priority flag for Cachix 🚩"
        run: nix-env --set-flag priority 0 cachix

      - name: "Build ${{ matrix.config_name }} Home Manager config 🏠"
        run: nix build .#homeConfigurations.${{ matrix.config_name }}.activationPackage -L
